package com.interview.pokemon_go.infrastructure.persistence;

import com.interview.pokemon_go.domain.model.Ability;
import com.interview.pokemon_go.domain.model.PokemonSummary;
import com.interview.pokemon_go.domain.model.Weight;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.tuple;

class PokemonPersistenceMapperTest {

    private static final String SPRITE = "https://example.org/25.png";

    @Test
    void mapsPokedexNumberToDomainId() {
        PokemonSummary summary = PokemonPersistenceMapper.toDomain(
                new PokemonEntity(25, "pikachu", SPRITE, "Mouse Pokémon", 60));

        assertThat(summary.id()).isEqualTo(25);
    }

    @Test
    void mapsEntityToDomain() {
        PokemonEntity entity = new PokemonEntity(25, "pikachu", SPRITE, "Mouse Pokémon", 60);
        entity.addAbility("static", false);
        entity.addAbility("lightning-rod", true);

        PokemonSummary summary = PokemonPersistenceMapper.toDomain(entity);

        assertThat(summary.id()).isEqualTo(25);
        assertThat(summary.name()).isEqualTo("pikachu");
        assertThat(summary.spriteUrl()).isEqualTo(SPRITE);
        assertThat(summary.category()).isEqualTo("Mouse Pokémon");
        assertThat(summary.weight().hectograms()).isEqualTo(60);
        assertThat(summary.weight().kilograms()).isEqualTo(6.0);
        assertThat(summary.abilities()).containsExactly(
                new Ability("static", false), new Ability("lightning-rod", true));
    }

    @Test
    void mapsDomainToEntity() {
        PokemonSummary summary = new PokemonSummary(4, "charmander", SPRITE, "Lizard Pokémon", new Weight(85),
                List.of(new Ability("blaze", false), new Ability("solar-power", true)));

        PokemonEntity entity = PokemonPersistenceMapper.toEntity(summary);

        assertThat(entity.getId()).as("id is generated by the database").isNull();
        assertThat(entity.getPokedexNumber()).isEqualTo(4);
        assertThat(entity.getName()).isEqualTo("charmander");
        assertThat(entity.getSpriteUrl()).isEqualTo(SPRITE);
        assertThat(entity.getCategory()).isEqualTo("Lizard Pokémon");
        assertThat(entity.getWeightHectograms()).isEqualTo(85);
        assertThat(entity.getAbilities())
                .extracting(AbilityEntity::getName, AbilityEntity::isHidden)
                .containsExactly(tuple("blaze", false), tuple("solar-power", true));
    }

    @Test
    void linksEachAbilityToItsPokemon() {
        PokemonSummary summary = new PokemonSummary(7, "squirtle", SPRITE, "Tiny Turtle Pokémon", new Weight(90),
                List.of(new Ability("torrent", false), new Ability("rain-dish", true)));

        PokemonEntity entity = PokemonPersistenceMapper.toEntity(summary);

        assertThat(entity.getAbilities()).allSatisfy(ability -> {
            assertThat(ability.getPokemon()).isSameAs(entity);
            assertThat(ability.getId()).as("id is generated by the database").isNull();
        });
    }

    @Test
    void roundTripPreservesSummary() {
        PokemonSummary summary = new PokemonSummary(1, "bulbasaur", SPRITE, "Seed Pokémon", new Weight(69),
                List.of(new Ability("overgrow", false)));

        assertThat(PokemonPersistenceMapper.toDomain(PokemonPersistenceMapper.toEntity(summary)))
                .isEqualTo(summary);
    }

    @Test
    void mapsEmptyAbilitiesAndNullOptionalFields() {
        PokemonEntity entity = new PokemonEntity(132, "ditto", null, null, 40);

        PokemonSummary summary = PokemonPersistenceMapper.toDomain(entity);

        assertThat(summary.abilities()).isEmpty();
        assertThat(summary.spriteUrl()).isNull();
        assertThat(summary.category()).isNull();
    }
}
